### ISSUE TITLE
tango-2-theme missing

### ISSUE THREAD

**Issue by ghost** [aborn/popkit-elpa#11]
I tried popkit-elpa recently. Awesome project by the way. Very helpful.

I noticed one little package is missing.
`Package tango-2-theme is unavailable. Is the package name misspelled?`
But I check the receipts in the ~popkit-elpa~, there is a 
[tango-2-theme](https://github.com/aborn/popkit-elpa/blob/master/recipes/tango-2-theme) receipt.

Is it because that the github ~gist~ services is blocked in China? Is there any workaround for this?

**Comment by aborn** [comment]
多谢!我会查一下这个问题

**Comment by aborn** [comment]
引起这个问题的原因是国内的vps服务器无法访问github的gist服务器，现已通过proxy模式修复。
