### ISSUE TITLE
使用popkit源安装perspective和persp-mode出错

### ISSUE THREAD

**Issue by winzhang0** [aborn/popkit-elpa#14]
安装persp-mode提示no such package kind: perspectives，安装perspective，提示：not such package kind: s，但是检查package s，发现已经正确安装。

使用describe-package查看persp-mode和perspective，都提示错误:Wrong Type argument，截图如下：
![package-install-error](https://cloud.githubusercontent.com/assets/19620951/15626257/53122746-24f3-11e6-9bb6-d6301312c34f.png)

**Comment by aborn** [comment]
这个包的描述里有双引号，之前没有转义，引发这个错误，现在已经修复。
原先为："perspectives" shared among frames + save/load  bugs.
修复后为：
\"perspectives\" shared among frames + save/load  bugs.
多谢提交issue，祝愉快！ @winzhang0

**Comment by winzhang0** [comment]
谢谢
