### ISSUE TITLE
Drupal mode缺失了drupal 目录的内容。

### ISSUE THREAD

**Issue by lixuzhang** [aborn/popkit-elpa#15]
# 以下是使用 popkit-elpa 安装drupal-mode时的输出。

Generating autoloads for drupal-mode.el...done
Wrote f:/msys64/home/lixuzhang/.emacs.d/elpa/drupal-mode-20160515.1920/drupal-mode-autoloads.el
Checking f:/msys64/home/lixuzhang/.emacs.d/elpa/drupal-mode-20160515.1920... [3 times]
Compiling f:/msys64/home/lixuzhang/.emacs.d/elpa/drupal-mode-20160515.1920/drupal-mode.el...
Checking f:/msys64/home/lixuzhang/.emacs.d/elpa/drupal-mode-20160515.1920...
Done (Total of 0 files compiled, 1 failed, 2 skipped)

---

导致启动时提示加载 drupal/pcomplete出错。

经查，drupal-mode 的安装目录缺少了drupal 目录。

**Comment by aborn** [comment]
这个问题已经修复，如有任何问题，可以加群进行反馈：537772301（popkit-elpa源，验证答案：elisp)
多谢提交issue，祝好！
