### ISSUE TITLE
geiser  安装完，安装目录没东西。

### ISSUE THREAD

**Issue by lixuzhang** [aborn/popkit-elpa#16]
Debugger entered--Lisp error: (error "Don’t call me!")
  signal(error ("Don’t call me!"))
  error("Don't call me!")
  define-package("geiser" "20160529.939" "GNU Emacs and Scheme talk to each other" nil)
  require(geiser nil noerror)
  (not (require (quote geiser) nil (quote noerror)))
  (if (not (require (quote geiser) nil (quote noerror))) (ignore (message (format "Cannot load %s" (quote geiser)))) (condition-case err (progn (req-package-handle-loading (quote (geiser (scheme))) (function (lambda nil (progn)))) (req-package-loaded (quote (geiser (scheme))))) ((debug error) (ignore (display-warning (quote use-package) (format "%s %s: %s" "geiser" ":config" (error-message-string err)) :error)))) t)
  (progn (condition-case err (progn (setq geiser-default-implementation scheme-program-name)) ((debug error) (ignore (display-warning (quote use-package) (format "%s %s: %s" "geiser" ":init" (error-message-string err)) :error)))) (if (not (require (quote geiser) nil (quote noerror))) (ignore (message (format "Cannot load %s" (quote geiser)))) (condition-case err (progn (req-package-handle-loading (quote (geiser (scheme))) (function (lambda nil (progn)))) (req-package-loaded (quote (geiser (scheme))))) ((debug error) (ignore (display-warning (quote use-package) (format "%s %s: %s" "geiser" ":config" (error-message-string err)) :error)))) t))
  eval((progn (condition-case err (progn (setq geiser-default-implementation scheme-program-name)) ((debug error) (ignore (display-warning (quote use-package) (format "%s %s: %s" "geiser" ":init" (error-message-string err)) :error)))) (if (not (require (quote geiser) nil (quote noerror))) (ignore (message (format "Cannot load %s" (quote geiser)))) (condition-case err (progn (req-package-handle-loading (quote (geiser (scheme))) (function (lambda nil (progn)))) (req-package-loaded (quote (geiser (scheme))))) ((debug error) (ignore (display-warning (quote use-package) (format "%s %s: %s" "geiser" ":config" (error-message-string err)) :error)))) t)))
  req-package-eval-form((use-package geiser :init (progn (setq geiser-default-implementation scheme-program-name)) :config (progn (req-package-handle-loading (quote (geiser (scheme))) (lambda nil (progn))) (req-package-loaded (quote (geiser (scheme)))))))
  #[nil "\301!\207" [EVAL req-package-eval-form] 2]()
  req-package-handle-loading((geiser (scheme)) #[nil "\301!\207" [EVAL req-package-eval-form] 2])
  req-package-eval((geiser (scheme)))
  #[(pkg) "\302\303    #\210\304!\207" [pkg req-package-deps-left puthash -1 req-package-eval] 4](%28geiser %28scheme%29%29)
  -each(((geiser (scheme)) (guile-scheme (scheme))) #[(pkg) "\302\303  #\210\304!\207" [pkg req-package-deps-left puthash -1 req-package-eval] 4])
  req-package-loaded((scheme nil))
  (progn (req-package-handle-loading (quote (scheme nil)) (function (lambda nil (progn)))) (req-package-loaded (quote (scheme nil))))
  (condition-case err (progn (req-package-handle-loading (quote (scheme nil)) (function (lambda nil (progn)))) (req-package-loaded (quote (scheme nil)))) ((debug error) (ignore (display-warning (quote use-package) (format "%s %s: %s" "scheme" ":config" (error-message-string err)) :error))))
  (if (not (require (quote scheme) nil (quote noerror))) (ignore (message (format "Cannot load %s" (quote scheme)))) (condition-case err (progn (req-package-handle-loading (quote (scheme nil)) (function (lambda nil (progn)))) (req-package-loaded (quote (scheme nil)))) ((debug error) (ignore (display-warning (quote use-package) (format "%s %s: %s" "scheme" ":config" (error-message-string err)) :error)))) t)
  (progn (condition-case err (progn (if (executable-find "guile") (progn (setq scheme-program-name "guile")))) ((debug error) (ignore (display-warning (quote use-package) (format "%s %s: %s" "scheme" ":init" (error-message-string err)) :error)))) (if (not (require (quote scheme) nil (quote noerror))) (ignore (message (format "Cannot load %s" (quote scheme)))) (condition-case err (progn (req-package-handle-loading (quote (scheme nil)) (function (lambda nil (progn)))) (req-package-loaded (quote (scheme nil)))) ((debug error) (ignore (display-warning (quote use-package) (format "%s %s: %s" "scheme" ":config" (error-message-string err)) :error)))) t))
  eval((progn (condition-case err (progn (if (executable-find "guile") (progn (setq scheme-program-name "guile")))) ((debug error) (ignore (display-warning (quote use-package) (format "%s %s: %s" "scheme" ":init" (error-message-string err)) :error)))) (if (not (require (quote scheme) nil (quote noerror))) (ignore (message (format "Cannot load %s" (quote scheme)))) (condition-case err (progn (req-package-handle-loading (quote (scheme nil)) (function (lambda nil (progn)))) (req-package-loaded (quote (scheme nil)))) ((debug error) (ignore (display-warning (quote use-package) (format "%s %s: %s" "scheme" ":config" (error-message-string err)) :error)))) t)))
  req-package-eval-form((use-package scheme :init (progn (when (executable-find "guile") (setq scheme-program-name "guile"))) :config (progn (req-package-handle-loading (quote (scheme nil)) (lambda nil (progn))) (req-package-loaded (quote (scheme nil))))))
  #[nil "\301!\207" [EVAL req-package-eval-form] 2]()
  req-package-handle-loading((scheme nil) #[nil "\301!\207" [EVAL req-package-eval-form] 2])
  req-package-eval((scheme nil))
  #[(key value) "\302  \303#\303\232\205

**Comment by aborn** [comment]
这个问题已经修好了，你试一下。原因是之前打成tar包的时候漏了一些文件，如有任何问题，可以加群进行反馈：537772301（popkit-elpa源，验证答案：elisp)
多谢提交issue，祝好！
