### ISSUE TITLE
Windows下无法连接popkit

### ISSUE THREAD

**Issue by ailisp** [aborn/popkit-elpa#20]
我在Windows下的没有做任何配置的官方emacs 24.5.1，添加popkit源后list-packages会提示Failed to download `popkit' archive. 而我的网络在Linux下的emacs 24.5是可以正常使用popkit的，这是为什么，应该怎么解决？谢谢

**Comment by aborn** [comment]
先检查下在windows下以下几个链接是否能访问：
https://elpa.popkit.org/#/
https://elpa.popkit.org/archive.json
https://elpa.popkit.org/recipes.json
https://elpa.popkit.org/packages/archive-contents

加这个Q群：537772301  验证：elisp

**Comment by ailisp** [comment]
问题解决了，可能是windows下的emacs 24.5对https的支持有bug，按aborn大神说的popkit的网址改成
 "http://elpa.popkit.org/packages/"（https改成http）就可以了

**Comment by aborn** [comment]
参照purcell的说法https://github.com/melpa/melpa/issues/3914 ，windows下emacs 24.3对https的支持，需要额外下载库的支持。

**Comment by aborn** [comment]
Windows下emacs 24.5及以下版本是不支持TLS，要手动安装一个TLS库，见这个http://www.lonecpluspluscoder.com/2015/08/01/adding-tls-support-to-emacs-24-5-on-windows/
