### ISSUE TITLE
error: Package `darcsum-' is unavailable

### ISSUE THREAD

**Issue by cfsmile** [aborn/popkit-elpa#21]
## 问题

启动emacs，警示以'--debug-init'方式排查错误。
Warning (initialization): An error occurred while loading `/home/.emacs.d/init.el':

**error: Package `darcsum-' is unavailable**
...
## 软件环境

emacs 24.5.1 
ubuntu 16.04LTS
Emacs配置用[Steve Purcell](https://github.com/purcell/emacs.d)的。
## 修改melpa源

又根据popkit-elpa教程，修改其.emacs.d/lisp/init-elpa.el 中 melpa源，如下

> diff -c /home/.emacs.d/lisp/init-elpa.el /home/.emacs.d/lisp/init-elpa.el.original
> **\* /home/.emacs.d/lisp/init-elpa.el    2016-09-04 22:50:17.720819883 +0800
> --- /home/.emacs.d/lisp/init-elpa.el.original   2016-09-04 22:21:34.612172522 +0800
> **\* 26,34 ****
>     (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))
>     ;;; Also use Melpa for most packages
> ! (add-to-list 'package-archives `("popkit" . ,(if (< emacs-major-version 24)
> !                                                 "http://elpa.popkit.org/packages/"
> !                                               "https://elpa.popkit.org/packages/")))
> 
> --- 26,34 ----
>     (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))
>     ;;; Also use Melpa for most packages
> ! (add-to-list 'package-archives `("melpa" . ,(if (< emacs-major-version 24)
> !                                                 "http://melpa.org/packages/"
> !                                               "https://melpa.org/packages/")))
> Diff finished.  Sun Sep  4 23:09:45 2016
## 没能排错

init.el中只有 (require 'init-darcs)，没有darcsum。
虽不影响使用，却没找到问题所在。

**Comment by aborn** [comment]
这个包之前下载到服务器有问题，已经fix。 http://elpa.popkit.org/#/darcsum 。多谢提交issue！

**Comment by cfsmile** [comment]
警示已消失。谢谢！
