### ISSUE TITLE
magit 需要添加  "lisp/magit-autorevert.el" 文件

### ISSUE THREAD

**Issue by lixuzhang** [aborn/popkit-elpa#3]
magit 需要添加  "lisp/magit-autorevert.el" 文件。

melpa源已经更新修改。
https://github.com/milkypostman/melpa/commit/5bee99e0516ef85aeeb1cfa59495215666ec7249
# 升级错误信息：

In toplevel form:
git-rebase.el:70:1:Error: Cannot open load file: no such file or directory, magit-autorevert

In toplevel form:
magit-apply.el:33:1:Error: Cannot open load file: no such file or directory, magit-autorevert

In toplevel form:
magit-bisect.el:30:1:Error: Cannot open load file: no such file or directory, magit-autorevert

In toplevel form:
magit-blame.el:31:1:Error: Cannot open load file: no such file or directory, magit-autorevert

In toplevel form:
magit-commit.el:32:1:Error: Cannot open load file: no such file or directory, magit-autorevert

In toplevel form:
magit-core.el:39:1:Error: Cannot open load file: no such file or directory, magit-autorevert

In toplevel form:
magit-diff.el:32:1:Error: Cannot open load file: no such file or directory, magit-autorevert

In toplevel form:
magit-ediff.el:30:1:Error: Cannot open load file: no such file or directory, magit-autorevert

In toplevel form:
magit-extras.el:27:1:Error: Cannot open load file: no such file or directory, magit-autorevert

In toplevel form:
magit-log.el:32:1:Error: Cannot open load file: no such file or directory, magit-autorevert

In toplevel form:
magit-remote.el:32:1:Error: Cannot open load file: no such file or directory, magit-autorevert

In toplevel form:
magit-sequence.el:32:1:Error: Cannot open load file: no such file or directory, magit-autorevert

In toplevel form:
magit-stash.el:30:1:Error: Cannot open load file: no such file or directory, magit-autorevert

In toplevel form:
magit-wip.el:33:1:Error: Cannot open load file: no such file or directory, magit-autorevert

In toplevel form:
magit.el:56:1:Error: Cannot open load file: no such file or directory, magit-autorevert

**Comment by aborn** [comment]
刚才与melpa同步了，今天晚点时候应该可以。

**Comment by wangjiezhe** [comment]
Missing `lisp/magit.el`
See milkypostman/melpa#3491

**Comment by aborn** [comment]
已经更新 https://github.com/aborn/popkit-elpa/commit/793f1d9d7e4356e4a451f134139f6f67afdee0f7
@wangjiezhe
