### ISSUE TITLE
镜像用不了啊

### ISSUE THREAD

**Issue by re-thinker** [aborn/popkit-elpa#4]
按照
          (require 'package) ;; You might already have this line
          (add-to-list 'package-archives
          '("popkit" . "http://elpa.popkit.org/packages/"))
          (when (< emacs-major-version 24)
          ;; For important compatibility libraries like cl-lib
          (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))
          (package-initialize) ;; You might already have this line
但下载失败

**Comment by aborn** [comment]
报什么错？
