### ISSUE TITLE
flycheck: 缺失flycheck-buttercup.el

### ISSUE THREAD

**Issue by lixuzhang** [aborn/popkit-elpa#5]
Leaving directory `f:/msys64/home/lixuzhang/.emacs.d/elpa/flycheck-20160216.1738'

Compiling file f:/msys64/home/lixuzhang/.emacs.d/elpa/flycheck-20160216.1738/flycheck-buttercup.el at Tue Feb 16 21:12:49 2016
Entering directory`f:/msys64/home/lixuzhang/.emacs.d/elpa/flycheck-20160216.1738/'
flycheck-buttercup.el:39:1:Error: Cannot open load file: no such file or directory, buttercup

Compiling file f:/msys64/home/lixuzhang/.emacs.d/elpa/flycheck-20160216.1738/flycheck-ert.el at Tue Feb 16 21:12:49 2016

Compiling file f:/msys64/home/lixuzhang/.emacs.d/elpa/flycheck-20160216.1738/flycheck.el at Tue Feb 16 21:12:50 2016

**Comment by aborn** [comment]
从日志上看是没找到 buttercup， 你先安装下buttercup试试http://elpa.popkit.org/#/buttercup  @lixuzhang
