### ISSUE TITLE
有些包无法下载

### ISSUE THREAD

**Issue by dochang** [aborn/popkit-elpa#6]
erlang 和 wsd-mode 这两个包，在 http://elpa.popkit.org/ 上搜索不到，也无法下载。但是 `recipes` 目录下还有这两个包的 recipe ，melpa 上也有这两个包。请检查一下这个问题

**Comment by aborn** [comment]
这两天在外旅游，不是很方便，过两天回去查下。多谢！

**Comment by aborn** [comment]
这两个包，确定有问题，应该是下载程序有问题

**Comment by dochang** [comment]
能修复吗？现在仍然搜不到这两个包

**Comment by aborn** [comment]
@dochang 这个问题还要查下，可能是现在服务器空间快不足了

**Comment by aborn** [comment]
已经修复！
