### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by gadmyth** [aborn/popkit-elpa#7]
File error: http://elpa.popkit.org/packages/tree-mode-20151104.2131.el, Forbidden

**Comment by aborn** [comment]
你再试试，现在应该能访问了 http://elpa.popkit.org/packages/tree-mode-20151104.2131.el

**Comment by DelightRun** [comment]
@aborn 为何不再配置个HTTPS呢？好像如果不写协议的话默认会用https

**Comment by aborn** [comment]
有这个必要，多谢@DelightRun 建议！

**Comment by xcodebuild** [comment]
@aborn @DelightRun  直接写

``` lisp
(defvar configuration-layer--elpa-archives
  '(("popkit" . "http://elpa.popkit.org/packages/")
    ("org"   . "orgmode.org/elpa/")
    ("gnu"   . "elpa.gnu.org/packages/"))
  "List of ELPA archives required by Spacemacs.")
```

就不会走https了

**Comment by aborn** [comment]
已经对https进行支持
https://elpa.popkit.org/#/
@DelightRun
