### ISSUE TITLE
Spacemacs用户应该要修改core-configuration-layer.el文件

### ISSUE THREAD

**Issue by DelightRun** [aborn/popkit-elpa#8]
Spacemacs对`package-archive`的配置在`core-configuration-layer.el`文件中，应该要修改这个文件。

路径：`~/.emacs.d/core/core-configuration-layer.el`

**Comment by aborn** [comment]
多谢@DelightRun 的建议，已经添加到[README.md](https://github.com/aborn/popkit-elpa)里
